services:
  spring:
    container_name: mph-server
    build: .
    restart: always
    ports:
      - 8001:8001
    env_file:
      - .env
    depends_on:
      - postgresql
    networks:
      - mph-network
      - traefik

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 1800
      WATCHTOWER_INCLUDE_RESTARTING: "true"
    command: --cleanup spring
    networks:
      - mph-network

volumes:
  postgres-data:

networks:
  mph-network:
  traefik:
    external: true