services:
  spring:
    container_name: mph-server
    image: ghcr.io/iodsky/motorph-api:latest
    restart: always
    ports:
      - 8001:8001
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.motorph.rule=Host(`motorph.iodsky.com`)"
      - "traefik.http.routers.motorph.entrypoints=websecure"
      - "traefik.http.routers.motorph.tls.certresolver=myresolver"
      - "traefik.http.services.orderly.loadbalancer.server.port=8001"
    networks:
      - mph-network
      - traefik
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 1800
      WATCHTOWER_INCLUDE_RESTARTING: "true"
    command: --cleanup spring
    networks:
      - mph-network

volumes:
  postgres-data:

networks:
  mph-network:
  traefik:
    external: true